apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  index.html: |-
    <h1>
    Hello World!
    <br>
    HIHI all!
    </h2>
